export const ARMAZENAR_FILMES = 'ARMAZENAR_FILMES';
export const BUSCAR_FILMES = 'BUSCAR_FILMES';
export const BUSCAR_FILME_POR_ID = 'BUSCAR_FILME_POR_ID';
export const EXCLUIR_FILME = 'EXCLUIR_FILME';
export const INSERIR_FILME = 'INSERIR_FILME';
export const SETAR_FILME_ATUAL = 'SETAR_FILME_ATUAL';